### ISSUE TITLE
Transforming bodies back to original coordinates system

### ISSUE THREAD

**Issue by ghost** [sanweiliti/PLACE#1]
Hi @sanweiliti , congrats on your great work.

I was wondering what is the correct order of transformations in order to transform the generated body vertices back to the original coordinates of the input scene.

To my understanding it should be:

rotate (-rot_angle_2)
scale (cube_size)
translate (-shift)
rotate (-rot_angle_1)

Could you please confirm whether these are indeed the correct transformations?

**Comment by sanweiliti** [comment]
hi @m-vasileiadis,

If you refer to the generated body vertices (direct output of the neural network), to transform it back to the original PROX coordinate system, the transformations are:

scale (cube_size)
translate (-shift)
rotate (-rot_angle_1)
as the input scene/body vertices for the neural network are in the local cube coordinate and scaled by cube_size

**Comment by ghost** [comment]
Yes that's exactly what I meant! Thanks for the clarification
